import { BNB, FANTOM, METIS, ChainId, CurrencyAmount, Network } from '@hyperjump-defi/sdk'
import tokens from 'config/constants/tokens'

const networks = [
  {
    name: 'BSC',
    network: Network.BSC,
    id: 56,
    url: process.env.REACT_APP_BSC_BASE_URL,
    networkTokenUsdFarmPid: 3,
    farmingTokenUsdFarmPid: 1,
    farmingTokenNetworkTokenFarmPid: 1,
    govTokenNetworkTokenFarmPid: 2,
    wrappedFarmingTokenPid: 14,
    coreFarms: [1, 2, 3],
    farmingToken: tokens.jump,
    govToken: tokens.hypr,
    networkToken: tokens.bnb,
    wrappedNetworkToken: tokens.wbnb,
    wrappedFarmingToken: tokens.xjump,
    timerScale: 1, // changed from 3 because all chains are calculated by secs
    farmMultiplierScale: 100,
    baseCurrencyAmount: CurrencyAmount.bnb,
    baseCurrency: BNB,
    swapTokenListUrl: 'https://tokens.hyperjump.app/tokens.json',
    scannerName: 'BSC Scan',
    approvalDomainName: 'Thugswap Street LP',
    votingLink: 'https://snapshot.org/#/bsc.hyperjumpdao.eth',
    bridgePath: 'https://www.binance.org/en/bridge?utm_source=Hyperjump',
    contractsLink: 'https://github.com/HyperJump-DeFi/HyperJump-Contracts',
    infoLink: 'https://bsc-info.hyperjump.app',
    supportedChainIds: [ChainId.BSC_MAINNET],
    vaultCompoundTime: '8 hours',
    localEmissionRate: 1.583940258751902587,
  },
  {
    name: 'FTM',
    network: Network.FANTOM,
    id: 250,
    url: process.env.REACT_APP_FTM_BASE_URL,
    networkTokenUsdFarmPid: 3,
    farmingTokenUsdFarmPid: 1,
    farmingTokenNetworkTokenFarmPid: 1,
    govTokenNetworkTokenFarmPid: 2,
    wrappedFarmingTokenPid: 12,
    coreFarms: [1, 2, 3],
    farmingToken: tokens.jump,
    govToken: tokens.aurora,
    networkToken: tokens.ftm,
    wrappedNetworkToken: tokens.wftm,
    wrappedFarmingToken: tokens.xjump,
    timerScale: 1,
    farmMultiplierScale: 100,
    baseCurrencyAmount: CurrencyAmount.ftm,
    baseCurrency: FANTOM,
    swapTokenListUrl: 'https://tokens.hyperjump.app/ftmswap.json',
    scannerName: 'FTM Scan',
    approvalDomainName: 'HyperSwap LP',
    votingLink: 'https://snapshot.org/#/ftm.hyperjumpdao.eth',
    bridgePath: '',
    contractsLink: 'https://github.com/HyperJump-DeFi/HyperJump-Contracts',
    infoLink: 'https://ftm-info.hyperjump.app',
    supportedChainIds: [ChainId.FTM_MAINNET],
    vaultCompoundTime: 'hour',
    localEmissionRate: 1.585489599188229325,
  },
  {
    name: 'BSC_TESTNET',
    network: Network.BSC_TESTNET,
    id: 97,
    url: process.env.REACT_APP_BSC_TESTNET_BASE_URL,
    networkTokenUsdFarmPid: 3, // BNB BUSD
    farmingTokenUsdFarmPid: 2, // JUMP BUSD
    farmingTokenNetworkTokenFarmPid: 1, // JUMP BNB
    govTokenNetworkTokenFarmPid: 1,
    wrappedFarmingTokenPid: 5,
    coreFarms: [1, 2, 3],
    farmingToken: tokens.jump,
    govToken: tokens.hypr,
    networkToken: tokens.bnb,
    wrappedNetworkToken: tokens.wbnb,
    wrappedFarmingToken: tokens.xjump,
    timerScale: 1, // changed from 3
    farmMultiplierScale: 100,
    baseCurrencyAmount: CurrencyAmount.bnb,
    baseCurrency: BNB,
    swapTokenListUrl:
      'https://gateway.pinata.cloud/ipfs/QmcUD9JjFmyTch3WkQprY48QNoseTCYkCu9XRtm5F4zUuY/bscTestnetTokens.json',
    scannerName: 'BSC Scan',
    approvalDomainName: 'Thugswap Street LP',
    votingLink: 'https://snapshot.org/#/bsc.hyperjumpdao.eth',
    bridgePath: 'https://www.binance.org/en/bridge?utm_source=Hyperjump',
    contractsLink: 'https://github.com/HyperJump-DeFi/HyperJump-Contracts',
    infoLink: '/analytics',
    supportedChainIds: [ChainId.BSC_TESTNET],
    vaultCompoundTime: '8 hours',
  },
  {
    name: 'METIS',
    network: Network.METIS,
    id: 1088,
    url: process.env.REACT_APP_METIS_BASE_URL,
    networkTokenUsdFarmPid: 1,
    farmingTokenUsdFarmPid: 2,
    farmingTokenNetworkTokenFarmPid: 3,
    govTokenNetworkTokenFarmPid: 4,
    wrappedFarmingTokenPid: 0,
    coreFarms: [0, 1],
    farmingToken: tokens.jump,
    govToken: tokens.hypr,
    networkToken: tokens.metis,
    wrappedNetworkToken: tokens.wmetis,
    wrappedFarmingToken: tokens.xjump,
    timerScale: 1, // changed from 3 because all chains are calculated by secs
    farmMultiplierScale: 100,
    baseCurrencyAmount: CurrencyAmount.metis,
    baseCurrency: METIS,
    swapTokenListUrl: 'https://tokens.hyperjump.app/metis.json',
    scannerName: 'Andromeda explorer',
    approvalDomainName: 'HyperJump Street LP',
    votingLink: 'https://snapshot.org/#/metis.hyperjumpdao.eth',
    bridgePath: '',
    contractsLink: 'https://github.com/HyperJump-DeFi/HyperJump-Contracts',
    infoLink: 'https://metis-info.hyperjump.app',
    supportedChainIds: [ChainId.METIS],
    vaultCompoundTime: '8 hours',
    localEmissionRate: 1.583940258751902587,
  },
]

export default networks
